#!/usr/bin/env bash
#
# RTF-backend conformance (#209), cross-format: every corpus RTF in
# tests/data/rtf/sources/ was generated by LibreOffice from a DOCX (or DOC)
# conformance source, so its Markdown is compared against **our own
# conversion of that source document** — the two pipelines share the
# serializer, so the diff measures exactly what the RTF path loses, with no
# serializer-era noise. (RTF has no Python-docling counterpart to diff
# against: upstream reads RTF only via LibreOffice.)
#
# Differences beyond the parser's control remain — the LibreOffice round-trip
# itself rewrites equations to plain text, re-anchors grouped/floating
# pictures and drops textbox positioning — so the realistic ceiling is below
# 100 %; track the numbers, not perfection.
#
# Regenerate the corpus after adding DOCX fixtures (needs LibreOffice):
#   soffice --headless --convert-to rtf tests/data/docx/sources/*.docx \
#     --outdir tests/data/rtf/sources
#   # plus tests/data/doc/sources/*.doc -> <stem>.doc.rtf
#
# Usage: scripts/conformance/rtf_conformance.sh

set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../.."

cargo build --release --quiet -p docling-cli
BIN=./target/release/docling-rs

# Whitespace-normalized comparison (same helper as pdf_groundtruth.sh): a
# spacing-only divergence counts as a normalized match.
norm() { sed -E 's/[[:space:]]+/ /g; s/^ +//; s/ +$//'; }

exact=0
nmatch=0
total=0
printf "%-38s %14s\n" "RTF" "DIFF-LINES"
printf "%-38s %14s\n" "---" "----------"
for rtf in tests/data/rtf/sources/*.rtf; do
  base="$(basename "$rtf" .rtf)"
  if [[ "$base" == *.doc ]]; then
    src="tests/data/doc/sources/$base"
  else
    src="tests/data/docx/sources/$base.docx"
  fi
  [ -f "$src" ] || { printf "%-38s %14s\n" "$base" "no source"; continue; }
  total=$((total + 1))
  out="$("$BIN" --no-stream "$rtf")"
  ref="$("$BIN" --no-stream "$src")"
  if [ "$out" = "$ref" ]; then
    exact=$((exact + 1))
    nmatch=$((nmatch + 1))
    printf "%-38s %14s\n" "$base" "exact"
  elif [ "$(printf '%s' "$out" | norm)" = "$(printf '%s' "$ref" | norm)" ]; then
    nmatch=$((nmatch + 1))
    printf "%-38s %14s\n" "$base" "ws-only"
  else
    lines="$(diff <(printf '%s\n' "$out") <(printf '%s\n' "$ref") | grep -c '^[<>]' || true)"
    printf "%-38s %14s\n" "$base" "$lines"
  fi
done

echo
echo "exact: $exact/$total, whitespace-normalized: $nmatch/$total"
