/* docling.rs — minimal C ABI for embedders (issue #193).
 *
 * Generated by cbindgen from crates/docling-ffi; do not edit by hand.
 * See crates/docling-ffi/README.md for usage and the options JSON keys. */

#ifndef DOCLING_H
#define DOCLING_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// An opaque conversion result. Exactly one of output/error is set; the
// output buffer always carries a trailing NUL byte (not counted by `len`)
// so textual formats read as C strings.
typedef struct DoclingResult DoclingResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Convert a document held in memory.
//
// `bytes`/`len` is the raw file content, `filename` selects the input
// format by its extension, and `options_json` is a JSON object of
// conversion options (`NULL` or `""` for defaults) — see the crate docs for
// the keys. The returned result is never NULL and must be released with
// [`docling_result_free`]; inspect [`docling_result_error`] before reading
// the output.
//
// # Safety
//
// `bytes` must point to `len` readable bytes (or be NULL with `len` 0);
// `filename` must be a NUL-terminated string; `options_json` may be NULL.
struct DoclingResult *docling_convert(const uint8_t *bytes,
                                      uintptr_t len,
                                      const char *filename,
                                      const char *options_json);

// The converted output, or NULL when the conversion failed. NUL-terminated
// (readable as a C string for `to` = `md` / `json` / `latex`); for binary output
// (`dclx`) pair it with [`docling_result_output_len`]. Owned by the result —
// valid until [`docling_result_free`].
//
// # Safety
//
// `result` must be a pointer returned by [`docling_convert`] (or NULL) that
// has not been freed.
const char *docling_result_output(const struct DoclingResult *result);

// The output's length in bytes (the trailing NUL is not counted); 0 when
// the conversion failed.
//
// # Safety
//
// `result` must be a pointer returned by [`docling_convert`] (or NULL) that
// has not been freed.
uintptr_t docling_result_output_len(const struct DoclingResult *result);

// The error message, or NULL when the conversion succeeded. Owned by the
// result — valid until [`docling_result_free`].
//
// # Safety
//
// `result` must be a pointer returned by [`docling_convert`] (or NULL) that
// has not been freed.
const char *docling_result_error(const struct DoclingResult *result);

// Release a result. NULL is a no-op; freeing the same pointer twice is
// undefined behavior (as with `free`).
//
// # Safety
//
// `result` must be NULL or a pointer returned by [`docling_convert`] that
// has not already been freed.
void docling_result_free(struct DoclingResult *result);

// The docling.rs version as a static NUL-terminated string — never freed.
const char *docling_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DOCLING_H */
